// Convert SNES video output to 800x480 40pin LCD

// `timescale 1ns / 1ps

module 
/*
#(
    parameter       SNES_H =        256,
    parameter       SNES_H =        256,
    parameter       SNES_V =        224,
    parameter       SNES_HMAX =     SNES_H-1,
    parameter       SNES_VMAX =     SNES_V-1,
    parameter       LCD_H =         800,
    parameter       LCD_HPW =       48,
    parameter       LCD_HBP =       40, 
    parameter       LCD_HFP =       112,
    parameter       // LCD_HFP =       92, // attempt to sp
    parameter       LCD_HBLANK =    LCD_HPW + LCD_HBP + LCD_HFP,
    parameter       LCD_HTOTAL =    LCD_H + LCD_HBLANK,
    parameter       LCD_V =         480,
    parameter       LCD_VPW =       3,
    parameter       LCD_VBP =       29,
    parameter       LCD_VFP =       8,
    parameter       LCD_VBLANK =    LCD_VPW + LCD_VBP + LCD_VFP,
    parameter       LCD_VTOTAL =    LCD_V + LCD_VBLANK
)
*/
snes2lcd(
    input           CLK, // snes clock, ~21.5 MHz
    input           RESETN,

    input           DOTCLK, // roughly CLK / 4
    input           HDE,
    input           VDE,
    input [14:0]    RGB5,
    input [8:0]     XS, // {OUT_X[7:0], DOTCLK}
    input [8:0]     YS, // {FIELD, OUT_Y[7:0]}

    input           LCD_PIXELCLK, // 800x480 lcd pixel clock, ~31.2 MHz
    output          LCD_VSYNC,
    output          LCD_HSYNC,
    output          LCD_DE,
    output [23:0]   LCD_DATA,

    input           OVERLAY,
    output [7:0]    OVERLAY_X,
    output [7:0]    OVERLAY_Y,
    input [14:0]    OVERLAY_COLOR
);

localparam  SNES_H =        256,
            SNES_V =        224,
            SNES_HMAX =     SNES_H-1,
            SNES_VMAX =     SNES_V-1,

            LCD_H =         800,
            LCD_HPW =       48,
            LCD_HBP =       40, 
            // LCD_HFP =       112,
            LCD_HFP =       102, // attempt to speed things up a bit so we don't get outpaced by SNES frames
            LCD_HBLANK =    LCD_HPW + LCD_HBP + LCD_HFP,
            LCD_HTOTAL =    LCD_H + LCD_HBLANK,

            LCD_V =         480,
            LCD_VPW =       3,
            LCD_VBP =       29,
            LCD_VFP =       8,
            LCD_VBLANK =    LCD_VPW + LCD_VBP + LCD_VFP,
            LCD_VTOTAL =    LCD_V + LCD_VBLANK;


// resulting timing:
// with input clock = 31.2 MHz (32.051ns)
// HTOTAL = 990
// HTIME = 990 * 32.051ns = 31.7308 us
// VTOTAL = 520
// VTIME = 520 * 31.7308 us = 16.500 ms
// frame rate = 60.606 fps. Slightly faster than the 60fps generated by snes2hdmi (including the snes pause stuff)
// which means that most of the time, the LCD output will finish a frame and have to wait before starting the next frame

wire [7:0] xpos = XS[8:1];
wire [7:0] ypos = YS[7:0];

reg [7:0] first_line_in_buffer /*verilator public*/;
reg [7:0] latest_line_in_buffer /*verilator public*/;
reg [7:0] latest_pixel_in_buffer /*verilator public*/;

// Need some block ram to save lines
// Each line is 256 pixels, 15 bits (so 2 bytes)
// and each block ram is 2kB
// A single BRAM can hold 4 lines
// 64 lines = 16 BRAM (but Gowin actually makes it 15 by using one-bit data)

localparam  BUFFER_LINES =  64,
            BUFFER_WIDTH =  $clog2(BUFFER_LINES);
reg [14:0]  linebuf [0:(SNES_H*BUFFER_LINES)-1];

// Memory access
// write port
localparam  MEM_ADDR_WIDTH = $clog2(BUFFER_LINES*SNES_H);
reg [MEM_ADDR_WIDTH-1:0] memw_addr;
reg [14:0] memw_data;
reg        memw_en;

always @(posedge CLK) begin
    if(memw_en)
        linebuf[memw_addr] <= memw_data;
        if(ypos[BUFFER_WIDTH-1:0] == 0) first_line_in_buffer <= ypos;
        latest_line_in_buffer <= ypos;
        latest_pixel_in_buffer <= xpos;
end

genvar i;
generate
    for(i=0; i < BUFFER_LINES; i = i + 1) begin: line_numbers
        reg [7:0] linenum /*verilator public*/;
        always @(posedge CLK) begin
            if(memw_en) begin
                if(ypos[BUFFER_WIDTH-1:0] == i) begin
                    linenum <= ypos;
                end
            end
        end
    end
endgenerate

// read port
wire [MEM_ADDR_WIDTH-1:0] memr_addr;
reg [14:0] memr_data;

always @(posedge LCD_PIXELCLK) begin
    memr_data <= linebuf[memr_addr];
end

// line buffer loading
// line address is wrapped around, so the buffer is reused every *BUFFER_LINES* lines
reg dotclk_r;
always @(posedge CLK) begin
    dotclk_r <= DOTCLK;

    memw_en <= 1'b0;
    if(DOTCLK && (~dotclk_r)) begin
        // rising edge of DOTCLK
        if(HDE && VDE) begin
            memw_addr <= {ypos[BUFFER_WIDTH-1:0], xpos};
            memw_data <= RGB5;
            memw_en <= 1'b1;
        end
    end
end

// LCD video timing generation
// Start frame when we receive the first n lines of SNES video
// Provides pixel / line counts to use with the scaling output
reg [$clog2(LCD_HTOTAL)-1:0] cx;
reg [$clog2(LCD_VTOTAL)-1:0] cy;
reg [1:0] lcd_output_state; // 0: pause, 1: go (saw SNES video), 2: keep going (saw SNES video while in state 1), 3: overlay
reg allow_state_promote; // prevent early promotion from state 1 to 2 when still within the trigger that got us in state 1
always @(posedge LCD_PIXELCLK or negedge RESETN) begin
    if(~RESETN) begin
        cx <= 'd0;
        cy <= 'd0;
        lcd_output_state <= 2'b00;
        allow_state_promote <= 1'b0;
    end
    else begin
        case (lcd_output_state)
        2'b00: begin
`ifdef SEPARATE_OVERLAY_CODE
            if(OVERLAY)
                lcd_output_state <= 2'b11;
            else 
`endif
            if(xpos == (SNES_HMAX[7:0]) && ypos == 8'd0 && HDE && VDE) begin
                // end of first line
                lcd_output_state <= 2'b01;
                allow_state_promote <= 1'b0;
            end
            if(OVERLAY)
                lcd_output_state <= 2'b01; // allow for overlay even if frames from SNES aren't arriving
        end
        2'b01: begin
            cx <= cx == LCD_HTOTAL-1'b1 ? 0 : cx + 1'b1;
            cy <= cx == LCD_HTOTAL-1'b1 ? cy == LCD_VTOTAL-1'b1 ? 0: cy + 1'b1 : cy;
            if((~allow_state_promote) && (ypos == 8'd1))
                allow_state_promote <= 1'b1;
            if(xpos == (SNES_HMAX[7:0]) && ypos == 8'd0 && HDE && VDE && allow_state_promote)
                lcd_output_state <= 2'b10;
            else if((cy == LCD_VTOTAL - 1'b1) && (cx == LCD_HTOTAL-1'b1))
                lcd_output_state <= 2'b00;
        end
        2'b10: begin
            cx <= cx == LCD_HTOTAL-1 ? 0 : cx + 1'b1;
            cy <= cx == LCD_HTOTAL-1 ? cy == LCD_VTOTAL-1 ? 0: cy + 1'b1 : cy;
            if((cy == LCD_VTOTAL-1) && (cx == LCD_HTOTAL-1))
                lcd_output_state <= 2'b01; 
        end
        2'b11: begin
`ifdef SEPARATE_OVERLAY_CODE
            // overlay state
            cx <= cx == LCD_HTOTAL-1'b1 ? 0 : cx + 1'b1;
            cy <= cx == LCD_HTOTAL-1'b1 ? cy == LCD_VTOTAL-1'b1 ? 0: cy + 1'b1 : cy;
            if(~OVERLAY)
                lcd_output_state <= 2'b00;
`else
            // illegal state
            lcd_output_state <= 2'b00;
            cx <= 0;
            cy <= 0;
`endif
        end
        endcase
    end
end



// Interpolation - nearest neighbor
// Using inputs of cx, cy figure out which pixel of the original 256x224 
// input stream should be shown.

// Uses fractional scaling counters (xcnt, ycnt)

reg [10:0] xcnt = 11'd0;
reg [10:0] ycnt = 11'd0;
reg active = 1'b0;
localparam YOUTMAX = LCD_V; // display is 800x480, so maximum vertical is 480
localparam XOUTMAX = 640; // scales to 4:3 (even though input is 8:7)
localparam XSTART = ((LCD_H - XOUTMAX) / 2) + LCD_HPW + LCD_HBP;
localparam XSTOP = XSTART + XOUTMAX;
reg [7:0] xout = 8'd0;
reg [7:0] yout = 8'd0;

reg [9:0] cy_r = 10'd0;

assign memr_addr =  {yout[BUFFER_WIDTH-1:0], xout};

wire [9:0] cy_active = (cy > (LCD_VPW + LCD_VBP)) ? (cy - (LCD_VPW + LCD_VBP)) : 0;

always @(posedge LCD_PIXELCLK) begin
    reg active_t;
    reg [10:0] xcnt_next;
    reg [10:0] ycnt_next;
    xcnt_next = xcnt + 256;
    ycnt_next = ycnt + 224;

    active_t = 0;
    if (cx == XSTART - 1) begin
        active_t = 1;
        active <= 1;
    end else if (cx == XSTOP - 1) begin
        active_t = 0;
        active <= 0;
    end

    if (active_t | active) begin        // increment xout
        xcnt <= xcnt_next;
        if (xcnt_next >= XOUTMAX) begin
            xcnt <= xcnt_next - XOUTMAX;
            xout <= xout + 1;
        end
    end

    cy_r <= cy_active;
    if (cy_active[0] != cy_r[0]) begin         // increment yout at new lines
        ycnt <= ycnt_next;
        if (ycnt_next >= YOUTMAX) begin
            ycnt <= ycnt_next - YOUTMAX;
            yout <= yout + 1;
        end
    end

    if (cx == 0) begin
        xout <= 0;
        xcnt <= 0;
    end
    
    if (cy_active == 0) begin
        yout <= 0;
        ycnt <= 0;
    end 

end
`ifdef SEPARATE_OVERLAY_CODE
// overlay rescaled to 768 x 448 (x3 horiz, x2 vert)
// we need 3 pixels wide for each overlay pixel due to the
// way it fetches pixel info
// so multiply the horizontal (256) by 3
localparam OVERLAY_WIDTH = SNES_H*3;
localparam OVERLAY_HEIGHT = SNES_V*2;
localparam OVERLAY_XSTART = ((LCD_H - OVERLAY_WIDTH) / 2) + LCD_HPW + LCD_HBP;
localparam OVERLAY_XSTOP = OVERLAY_XSTART + OVERLAY_WIDTH;
localparam OVERLAY_YSTART = ((LCD_V - OVERLAY_HEIGHT) / 2) + LCD_VPW + LCD_VBP;
localparam OVERLAY_YSTOP = OVERLAY_YSTART + OVERLAY_HEIGHT;
reg overlay_active_y = 1'b0;
reg overlay_active_x = 1'b0;
reg [9:0] prev_y = 10'h0;
reg [1:0] overlay_xcnt = 2'h0;
reg [1:0] overlay_ycnt = 2'h0;
reg [7:0] overlay_xout = 8'h0;
reg [7:0] overlay_yout = 8'h0;
always @(posedge LCD_PIXELCLK) begin
    prev_y <= cy;

    if(cy == OVERLAY_YSTART) begin
        overlay_active_y <= 1'b1;
        overlay_yout <= 8'h0;
        overlay_ycnt <= 2'h0;
    end
    else if(cy == OVERLAY_YSTOP)
        overlay_active_y <= 1'b0;

    if(cx == OVERLAY_XSTART - 2) begin
        overlay_active_x <= 1'b1;
        overlay_xout <= 8'h0;
        overlay_xcnt <= 2'h0;
    end
    else if(cx == OVERLAY_XSTOP)
        overlay_active_x <= 1'b0;

    if(overlay_active_x && overlay_active_y) begin
        overlay_xcnt <= overlay_xcnt + 1;
        if(overlay_xcnt == 2'd2) begin
            overlay_xcnt <= 0;
            overlay_xout <= overlay_xout + 1;
        end
        if(prev_y[0] != cy[0]) begin
            overlay_ycnt <= overlay_ycnt + 1;
            if(overlay_ycnt == 2'd1) begin
                overlay_ycnt <= 0;
                overlay_yout <= overlay_yout + 1;
            end
        end

    end
end

assign OVERLAY_X = overlay_xout;
assign OVERLAY_Y = overlay_yout;
`else
assign OVERLAY_X = xout;
assign OVERLAY_Y = yout;
`endif

reg [23:0] rgb_out;

always @(posedge LCD_PIXELCLK) begin
    if(active) begin
        if(OVERLAY)
            rgb_out <= {OVERLAY_COLOR[4:0],3'b0,OVERLAY_COLOR[9:5],3'b0,OVERLAY_COLOR[14:10],3'b0};
        else
            rgb_out <= {memr_data[4:0], 3'b0, memr_data[9:5], 3'b0, memr_data[14:10], 3'b0};
    end else begin
        rgb_out <= 24'h303030;
    end
end

assign LCD_VSYNC = (cy < LCD_VPW) && lcd_output_state != 2'b00;
assign LCD_HSYNC = (cx < LCD_HPW) && lcd_output_state != 2'b00;
wire lcd_hde = (cx >= (LCD_HPW+LCD_HBP)) && (cx < (LCD_HPW+LCD_HBP+LCD_H));
wire lcd_vde = (cy >= (LCD_VPW+LCD_VBP)) && (cy < (LCD_VPW+LCD_VBP+LCD_V));
assign LCD_DE = lcd_hde & lcd_vde;
assign LCD_DATA = rgb_out;

endmodule
